name: Run Tests

on:
  push:
    branches:
      - main  

defaults:
  run:
    shell: bash
    working-directory:  src/test
    env:
      NODE_VERSION: 16

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16  # Ajuste esto a la versión de Node.js que necesita

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm run test